enabled = true
name = "MegaMix+ Free Camera"
author = "mos9527"
description = """
Introduces Free Camera to MegaMix+
NOTE : Works with controllers only! Seek alternatives if you're using KB&M (i.e. modded TLAC camera)
====
CONTROLS (w/ Xbox controller)
====
Hotkeys
- Press both LS + RS to toggle Camera Control / Normal Gameplay
- Dpad Up + Press RS to toggle ImGui
Camera Controls
- [ Left  Stick ] Moves camera in viewing direction
                  Press LS to move faster
- [ Right Stick ] Pans camera viewport
                  Press RS to move faster
- [    LB/RB    ] Moves camera up/down
- [    LT/RT    ] Decreases/increases FOV (Zooms in/out)
- [  Dpad L/R   ] Rotates viewport counter-clockwise/clockwise			
====
ACKNOWLEDGEMENTS
Original TLAC Camera by samyuu
	github.com/samyuu/TotallyLegitArcadeController
Modified TLAC CameraController to work with MM+ by BroGamer4256
	github.com/BroGamer4256/camera
===
"""
date = "14.06.2023"
version = "0.0.1b"
dll = [
"MMFreeCamera.dll",
]